# spatial config file

merscope_save_path: "//allen/programs/celltypes/workgroups/rnaseqanalysis/NHP_spatial/MERSCOPE/macaque"
stereoseq_save_path: "//allen/programs/celltypes/workgroups/rnaseqanalysis/NHP_spatial/BGI"
mapping_dir: "/mapping"
segmentation_dir: "/segmentation"
merscope_lims_code: "mfishMERSCOPEmacaqueAtlas"
lims_code: "macaqueAtlas"
bulkseq_file: "//allen/programs/celltypes/workgroups/rnaseqanalysis/NHP_spatial/bulkseq/macaque/master_bulk_data.csv"
stereoseq_qc_genes_file: "//allen/programs/celltypes/workgroups/rnaseqanalysis/NHP_spatial/BGI/QC_Genes_Stereoseq.csv"