# spatial config file
# put this one directory up from sis/

merscope_save_path: "//allen/programs/celltypes/workgroups/rnaseqanalysis/NHP_spatial/MERSCOPE/macaque"
stereoseq_save_path: "//allen/programs/celltypes/workgroups/rnaseqanalysis/NHP_spatial/BGI/Production"
storage_provider: "Isilon::POSIX"  # for S3 change to AWS::S3
mapping_dir: "mapping"
segmentation_dir: "segmentation"
qc_dir: "qc_doublets"
merscope_lims_code: "mfishMERSCOPEmacaqueAtlas"
lims_code: "macaqueAtlas"
bulkseq_file: "//allen/programs/celltypes/workgroups/rnaseqanalysis/NHP_spatial/bulkseq/macaque/master_bulk_data.csv"
stereoseq_qc_genes_file: "//allen/programs/celltypes/workgroups/rnaseqanalysis/NHP_spatial/BGI/QC_Genes_Stereoseq.csv"
taxonomy_info: 
    AIT20: 
        path: '//allen/programs/celltypes/workgroups/rnaseqanalysis/shiny/10x_seq/NHP_MTG_AIT_20'
        col_labels: ['class_', 'neighborhood_', 'subclass_', 'cluster_']
    AIT115: 
        path: '//allen/programs/celltypes/workgroups/rnaseqanalysis/shiny/10x_seq/NHP_BG_AIT_115' 
        col_labels: ['level1.class_', 'level2.neighborhood_', 'level3.subclass_', 'cluster_']
    GreatApes_Macaque:
        path: '//allen/programs/celltypes/workgroups/rnaseqanalysis/shiny/10x_seq/GreatApes_Macaque'
        col_labels: ['class_', 'neighborhood_', 'subclass_', 'cluster_']
        file: 'GreatApes_Macaque.h5ad'
    BICCN_M1_Macaque:
        path: '//allen/programs/celltypes/workgroups/rnaseqanalysis/shiny/10x_seq/BICCN_M1_Macaque'
        col_labels: ['class_Bakken_2022_', 'subclass_Bakken_2022_', 'cluster_']
        file: 'BICCN_M1_Macaque.h5ad'
hpc_outputs: '//allen/programs/celltypes/workgroups/rnaseqanalysis/NHP_spatial/hpc-jobs'
